---
title: 'STA 663: Graduate Project'
author: "Brian N. White"
date: "4/7/2020"
output:
  pdf_document: default
  html_document: default
---

### Summary

```{r load library, message=FALSE}
library(tidyverse)
library(tidymodels)
library(ranger)
```

### The Data

### Research Question

Can one use the combat statistics of a pokemon to predict whether or not that pokemon is legendary?

### The Model

### Model Fitting

```{r load library, message=FALSE}
library(tidyverse)
library(tidymodels)
library(ranger)
```


```{r load and attach data}
pokemon=read.csv("data/Pokemon.csv")
```

```{r proportion of legendary pokemon in data}
summary(pokemon$Legendary)
```

```{r prepare data for model}
set.seed(7)

poke_cv=vfold_cv(pokemon, v=10)
```


```{r tune random forest, cache=TRUE}
set.seed(7)
rf_tune=rand_forest(mode="classification",
                    mtry=floor(sqrt(6)),
                               trees=tune())  %>%
  set_engine("ranger", importance="impurity")

grid=expand.grid(trees=c(10, 25, 50, 100, 200, 300))

poke_tune=tune_grid(rf_tune,
                     Legendary~Total + HP + Attack + Defense + Sp..Atk + Sp..Def + Speed,
                     grid=grid,
                     resamples=poke_cv,
                     metrics=metric_set(gain_capture, accuracy))

#results of tuning
poke_tune %>%
  collect_metrics() %>%
  filter(.metric == "gain_capture") %>%
  arrange(desc(mean))

best_tree <- poke_tune %>%
  select_best(metric = "gain_capture") %>%
  pull()
```

```{r fit tuned random forest}
rf_best=rand_forest(mode="classification",
                    mtry=floor(sqrt(6)),
                               trees=best_tree) %>%
  set_engine("ranger", importance="impurity")

poke_best=fit(rf_best, 
               Legendary~Total + HP + Attack + Defense + Sp..Atk + Sp..Def + Speed,
               data=pokemon)
```

### Performance

```{r plot confusion matrix}
poke_best %>%
  predict(new_data = pokemon) %>%
  bind_cols(pokemon) %>%
  conf_mat(truth = Legendary, estimate = .pred_class) %>%
  autoplot(type = "heatmap")
```
```{r false positive and false negative rates}
x=predict(poke_best, pokemon)
pokemon=mutate(pokemon, predicted_class=x$.pred_class)

pokemon %>%
  summarise(fpr = 
              sum(Legendary == "False" & predicted_class == "True") /
              sum(Legendary == "False"),
            fnr = 
              sum(Legendary == "True" & predicted_class == "False") /
              sum(Legendary == "True"))
```

```{r variable importance}
#variable importance
var_imp=ranger::importance(poke_best$fit)

#data frame created for use in plot
var_imp_df <- data.frame(
  variable = names(var_imp),
  importance = var_imp
  )

#plot of variable importance in the model w.r.t. the Gini index
var_imp_df %>%
ggplot(aes(x = variable, y = importance)) +
  geom_col() + 
  coord_flip()
```